language: python - "3.8"

install:
    - pip install sphinx sphinx-rtd-theme

script:
    - make html
    - touch _build/html/.nojekyll

deploy:
  provider: pages:git
  github_token: $GITHUB_TOKEN
  edge: true
  keep_history: true
  local_dir: _build/html
  on:
    branch: master

